apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  labels:
    {{- include "oai-udm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http1
      # Port accessible outside cluster
      port: {{ .Values.config.sbiPortHttp1 }}
      # Port to forward to inside the pod
      targetPort: {{ .Values.config.sbiPortHttp1 }}
      protocol: TCP
    - name: http2
      # Port accessible outside cluster
      port: {{ .Values.config.sbiPortHttp2 }}
      # Port to forward to inside the pod
      targetPort: {{ .Values.config.sbiPortHttp2 }}
      protocol: TCP
  selector:
    {{- include "oai-udm.selectorLabels" . | nindent 4 }}
