{{- if .Values.persistent.sharedvolume }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cn5g-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.persistent.volumeName }}
  resources:
    requests:
      storage: {{ .Values.persistent.size }}
{{- end }}
