apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: proxy
        image: tolgaomeratalay/reverseproxy:v1.2
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        ports:
        - containerPort: 11095
        env:
        - name: SERVICENAME
          value: "test"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
