apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "mysql.fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: "/home/nsslm/sharedpvmysql"
  #mountOptions:
  #  - hard
  #  - nfsvers=4.1
  #nfs:
    #path: {{ .Values.persistence.volumePath | quote }}
    #server: 192.168.2.73
