apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mysql.fullname" . }}-pvclaim
spec:      
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  storageClassName: standard
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  volumeName: {{ template "mysql.fullname" . }}-pv
