# Use the latest Ubuntu image for the base.
FROM ubuntu:focal

# Install the iptables command.
RUN apt-get update && \
    apt-get install -y iptables wget curl net-tools vim

RUN wget https://dl.google.com/go/go1.19.5.linux-amd64.tar.gz
RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.19.5.linux-amd64.tar.gz

ENV PATH="$PATH:/usr/local/go/bin"

COPY ./* /usr/src/
WORKDIR /usr/src/

CMD ["sleep", "infinity"]
