apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleclient
  labels:
    app: sampleclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleclient
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sampleclient
      annotations:
        k8s.v1.cni.cncf.io/networks: ext-net1
    spec:
      nodeSelector:
        type: run
      initContainers:
      - name: init-networking
        image: tolgaomeratalay/init-networking:v5
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: service
        image: tolgaomeratalay/sampleclient:v1.0
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command:
          - /bin/sleep
          - infinity
      - name: proxy
        image: tolgaomeratalay/reverseproxy:v1.1
        ports:
        - containerPort: 11095
        securityContext:
          privileged: true
        env:
        - name: SERVICENAME
          value: "sampleclient"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
